# Generated by Django 2.2.28 on 2025-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='MEquipment',
            fields=[
                ('equipment_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('equipment_type_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'm_equipment',
            },
        ),
        migrations.CreateModel(
            name='MEquipmentType',
            fields=[
                ('equipment_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('equipment_type_description', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'm_equipment_type',
            },
        ),
        migrations.CreateModel(
            name='MLocation',
            fields=[
                ('location_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'm_location',
            },
        ),
        migrations.CreateModel(
            name='MParameter',
            fields=[
                ('parameter_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parameter_description', models.CharField(max_length=255)),
                ('parameter_value_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'm_parameter',
            },
        ),
        migrations.CreateModel(
            name='MParameterMeasure',
            fields=[
                ('parameter_measure_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parameter_measure_unit', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'm_parameter_measure',
            },
        ),
        migrations.CreateModel(
            name='MParameterValue',
            fields=[
                ('parameter_value_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parameter_value_description', models.CharField(max_length=255)),
                ('parameter_measure_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'm_parameter_value',
            },
        ),
        migrations.CreateModel(
            name='MRole',
            fields=[
                ('role_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('role_description', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'm_role',
            },
        ),
        migrations.CreateModel(
            name='MSubLocation',
            fields=[
                ('sub_location_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sub_location_name', models.CharField(max_length=100)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'm_sub_location',
            },
        ),
        migrations.CreateModel(
            name='MUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=100)),
                ('primary_mobile_number', models.CharField(max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role_id', models.IntegerField()),
                ('user_password', models.CharField(max_length=50)),
                ('secondary_mobile_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user_address_1', models.CharField(max_length=255)),
                ('user_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('last_login', models.DateField(blank=True, null=True)),
                ('login_count', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('employment_type_id', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('conractor_id', models.IntegerField(blank=True, null=True)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('designation_id', models.IntegerField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('qualification_id', models.IntegerField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'm_user',
            },
        ),
        migrations.CreateModel(
            name='TEquipmentLocation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('equipment_id', models.IntegerField(blank=True, null=True)),
                ('sub_location_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_equipment_location',
            },
        ),
        migrations.CreateModel(
            name='TEquipmentTypeParameterValueMeasure',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('equipment_id', models.IntegerField(blank=True, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('parameter_id', models.IntegerField(blank=True, null=True)),
                ('value_id', models.IntegerField(blank=True, null=True)),
                ('measure_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_equipment_type_parameter_value_measure',
            },
        ),
        migrations.CreateModel(
            name='TLocationSublocation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('sub_location_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_location_sublocation',
            },
        ),
        migrations.CreateModel(
            name='TUserRole',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_user_role',
            },
        ),
    ]
