# Generated by Django 2.2.28 on 2025-06-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MState',
            fields=[
                ('sm_state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sm_state_name', models.CharField(max_length=20)),
                ('sm_visible', models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ('sm_modified_date', models.DateTimeField(blank=True, null=True)),
                ('sm_modified_by', models.CharField(blank=True, max_length=25, null=True)),
                ('sm_ip_addr', models.CharField(blank=True, max_length=15, null=True)),
                ('sm_remarks', models.CharField(blank=True, max_length=2000, null=True)),
                ('sm_state_hindi', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'm_state',
                'managed': False,
            },
        ),
    ]
